image: artifactory.wbaa.pl.ing.net/registry/python:3.6

stages:
  - lint

lint:
  stage: lint
  tags: [docker-tag]
  script:
    - python3 -m pip install --user flake8 mypy
    - python3 -m flake8
    - python3 -m mypy --ignore-missing-imports .
